README.md
schema.go

Convenience:
In addition to this:
```go
space_devs := schema.Spaces["devs"]
index_devs_primary := space_devs.Indexes["primary"]
var res_devs []DevEnt
err := client.SelectTyped(space_devs.Id, index_devs_primary.Id, 0, 10, tarantool.IterAll, []interface{}{}, &res_devs)
```
it's now possible to do this, seems more intuitive:
```go
space_devs := schema.Spaces["devs"]
index_devs_primary := space_devs.Indexes["primary"]
var res_devs []DevEnt
err := client.SelectTyped(space_devs, index_devs_primary, 0, 10, tarantool.IterAll, []interface{}{}, &res_devs)
```
Note that ".Id" can be omitted on both Space and Index.

Make possible to pass Space and Index objects into Select etc.

---

request.go
tarantool_test.go

In many cases, we need write code like this:
```
var tuples []Tuple
Select(..., ..., 0, 1, IterEq, &tuples)
if len(tuples) != 1 {
return 
}
result = tuples[0]
``` 
Tarantool cli has (binary protocol - no) `get` func for shorthand select()[1]. I suggest to add this feature.
Code worked and tested in my cases, but we need tests in this package. In this week i will done this todo:
Now we can pass pointer one tuple:
```
var tuple Tuple
conn.GetTyped(space, key, &tuple)
```
What do you think about this?

Get feature

---

connection.go

Is more suitable for mocking than setup Schema due to an exported variable.

SetSchema method for the connection

---

connection.go

Preventing panic if address to tarantool endpoint is short

fixed index out of range panic on dial() to short address

---

connection.go

Past participle for "put" is "put"

Typo fixed in Opts.Reconnect description

---

queue/queue.go

There is invalid query in [queue/queue.go:149](https://github.com/tarantool/go-tarantool/blob/master/queue/queue.go#L148), `null` is used instead of `nil`:
```go
cmd := "local name = ... ; return queue.tube[name] ~= null"
resp, err := q.conn.Eval(cmd, []string{q.name})
```
When queue.Exists() is called, it throws an error:
```
eval:1: variable 'null' is not declared
```
This pr fixes that.

Queue "Exists" method evals wrong query

---

example_test.go
tarantool_test.go

Issue is described in #105. After further investigation, it was found that it was meant to be "insert structure using space name" test case that must process with success instead of "duplicate key error". Test case and corresponding output was changed to be consistent in first commit.
Before patch test case:
https://github.com/tarantool/go-tarantool/blob/61f3a41907b6bcb060e9fa07069cde5b33ba9764/example_test.go#L121-L125
Since there is a duplicate key error test case in another file, coverage has not decreased. 
https://github.com/tarantool/go-tarantool/blob/61f3a41907b6bcb060e9fa07069cde5b33ba9764/tarantool_test.go#L437-L443
Closes #105

Fix duplicate key test case

---

.github/workflows/testing.yml

In the provided workflow we install tarantool (1.10, 2.8, 2.9)
and just run tests from the module against it.
Closes #114

github-ci: add simple CI based on GitHub actions

---

README.md

readme: update link to tarantool manual

---

README.md

Add [FZambia/tarantool](https://github.com/FZambia/tarantool) connector to README "Alternative connectors" section. Add a link to feature comparison table in documentation.
Closes #138

readme: update "Alternative connectors" section

---

.github/workflows/reusable_testing.yml
.github/workflows/testing.yml
queue/config.lua
queue/queue_test.go

tests: queue tests fix 
Before this patch, queue tests failed due to impossibility to use _queue_taken,
which was deprecated in tarantool/queue [1]. Switch to _queue_taken_2 fixed it. 
Create access and some other actions were denied for test user. 
Additional grants fixed this problem.
The test `TestUtube_Put` was affected by replacing timeout in the call 
of `TakeTimeout()` with timeout of connection structure. For clarification 
of this effect see annotation for function `TakeTimeout()` [2]. That was 
fixed by making connection timeout longer than the timeout in the function call.
The step in testing.yml was uncommented for enabling queue tests in CI.
1. [queue/_queue_taken_2](https://github.com/tarantool/queue/tree/7d05b6db5b0d596db4281d53b57811e156234a0d#fields-of-the-_queue_consumers …

tests: queue tests fail

---

.github/pull_request_template.md
CHANGELOG.md

Changelog contains commits added after tagging of alpha version (commit
855df82a175cb5c1c2a52778a70ca56381c5963e). Changelog entries and format
conforms to format described in "Keep a changelog" [1].
1. https://keepachangelog.com/en/1.0.0/

Add initial version of changelog

---

README.md

After PR #151 Go requirement in README was bumped to version 1.13.
But README still contains a line describing version 1.3. This patch fixes it.
Related issues :#123

readme: make Go versions consistent

---

.github/workflows/check.yaml
CONTRIBUTING.md
connection.go
connection_pool/connection_pool_test.go
connection_pool/const.go
connection_pool/example_test.go
example_custom_unpacking_test.go
example_test.go
multi/multi_test.go
queue/example_msgpack_test.go
queue/example_test.go
queue/queue_test.go
response.go
schema.go
tarantool_test.go
test_helpers/main.go
test_helpers/pool_helper.go
uuid/uuid_test.go

code health: fix all places highlighted by linter
Changed the warning's suppression in check.yaml. The suppression of the rule
`errcheck` may be removed after adding errors check in all methods
with calling encodeXxx inside. See details below.
Suppressed the highlighting lacks of error's check in all methods,
having encodeXxx inside. For now those methods are not able to
return any error due to internal implementation of writer
interface (see smallbuf.go). For future, if the implementation of the writer
will be changed, and there will be a need to check errors, we must think
about how to say to compiler that the error check is 'unlikely' for keeping performance
(If there will be any affect on it).
Fixed the use of time package API in all places with calls of
time.Now().Sub(). Now time …

Fix lint warnings

---

CHANGELOG.md
config.lua
connector.go
const.go
example_custom_unpacking_test.go
example_test.go
multi/multi.go
request.go
response.go
tarantool_test.go

This patch adds the support of SQL in connector.
Added SQL tests. Updated config.lua for creation the space for 
using SQL in tests. Added the check of Tarantool version to skip SQL 
tests if Tarantool version < 2.0.0.
Fixes https://github.com/tarantool/go-tarantool/issues/62

Add minimal sql support

---

.github/workflows/check.yaml
CONTRIBUTING.md
Makefile
example_custom_unpacking_test.go
example_test.go
multi/example_test.go
queue/example_msgpack_test.go
tarantool_test.go

Some source files have an alphabet order of imports, some have not. It confuses me. I propose to replace `gofmt` with `goimports`:
[goimports](https://golangci-lint.run/usage/linters/) linter for `golangci-lint` checks if imports are sorted in the alhabet order. In addition to checking imports, goimports also checks the code formatting in the same style as gofmt so it can be used as a replacement.
Also, I added targets to the Makefile to make it easier to run [the formatter ](https://pkg.go.dev/golang.org/x/tools/cmd/goimports)and the linter locally.

Replace gofmt with goimports for golangci-lint

---

.github/workflows/testing.yml

Pull requests from outside collaborators don't have access to the repository secrets, see #156 as example.
I am not familiar with github actions. So I just copy a solution from [crud](https://github.com/tarantool/crud/blob/master/.github/workflows/test_on_push.yaml) and [tt](https://github.com/tarantool/tt/blob/master/.github/workflows/tests.yml). I'm ready to do something different if you have an example or a better idea.

github-ci: don't run ee tests for outside pull requests by default

---

CHANGELOG.md
config.lua
connection.go
const.go
example_test.go
future.go
future_test.go
request.go
response.go
response_it.go
tarantool_test.go

This patch adds support for receiving messages sent using box.session.push()
via an iterator in the manner of asynchronous case of a Lua implementation[1].
Now the calls Future.Get() and Future.GetTyped() ignore push messages, and
do not report an error.
1. https://www.tarantool.io/ru/doc/latest/reference/reference_lua/box_session/push/
Closes #67
I'm not particularly familiar with Go. So I most likely made mistakes in some basic and idiomatic things

Support IPROTO_PUSH messages

---

.github/workflows/testing.yml
CHANGELOG.md
Makefile
datetime/config.lua
datetime/datetime.go
datetime/datetime_test.go
datetime/example_test.go
decimal/decimal.go
decimal/decimal_test.go
decimal/example_test.go

This patch provides datetime support for all space operations and as
function return result. Datetime type was introduced in Tarantool 2.10.
See more in issue [1].
1. https://github.com/tarantool/tarantool/issues/5946
Closes #118

Datetime support

---

.github/workflows/testing.yml

Tarantool 2.10 can be installed with the setup-tarantool GitHub action.
Now the workaround for https://github.com/tarantool/setup-tarantool/issues/19 is not needed, because tarantool-2.10+ releases are supported since setup-tarantool v1.3.0.
The action uses the GitHub's caching infrastructure to speed up tarantool installation.

github-ci: remove Tarantool 2.10 setup workaround

---

CHANGELOG.md
connection_pool/connection_pool.go
future.go

Before we do a release 1.7.0 I propose a little change: remove NewErrorFuture function from the public API.
It was introduced in e9b9ba1e . The function looks strange in the public API. The patch moves it to the connection_pool's internal implementation.

api: remove NewErrorFuture

---

call_16_test.go
call_17_test.go
connection.go
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go
connection_pool/example_test.go
connector.go
example_test.go
multi/multi.go
request.go
tarantool_test.go

Before we do a release 1.7.0 I propose a little change: left only an asynchronous version of Connection.Do.
In fact existing now Connection.Do() and Connection.DoTyped() are just wrappers for other public API calls. We can remove it without consequences. A client code will not suffer much. Before:
```Go
resp, err := conn.Do(req)
err := conn.DoTyped(req, &tup)
fut := conn.Do(req)
```
After:
```Go
req, err := Conn.Do(req).Get()
err := conn.Do(req).GetTyped(&tup)
fut := conn.Do(req)
```
So there are reasons for the patch:
1. It helps to make the public API shorter.
2. It makes the asynchronous essence of the connector is more clear.
3. It helps not to spread the unnecessary API to submodules.
4. We will have more freedom for changes in …

api: left only asynchronous Connection.Do(request)

---

datetime/datetime.go
datetime/datetime_test.go
datetime/example_test.go

The patch adds check for supported Datetime values. The supported range
comes from Tarantool implementation [1] and c-dt library [2].
1. https://github.com/tarantool/tarantool/blob/a99ccce5f517d2a04670289d3d09a8cc2f5916f9/src/lib/core/datetime.h#L44-L61
2. https://github.com/tarantool/c-dt/blob/e6214325fe8d4336464ebae859ac2b456fd22b77/API.pod#introduction
I didn't add an entry to CHANGELOG.md because there hasn't been a release since datetime support. But I can add if necessary.
Closes #191

datetime: sync datetime range with Tarantool

---

CHANGELOG.md
go.mod
go.sum

It fixes build with OpenSSL < 1.1.1 [1] on CetnOS 7.
1. https://github.com/tarantool/go-openssl/pull/7

mod: bump version of go-openssl

---

CHANGELOG.md
connection.go
connection_pool/config.lua
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go
connection_pool/example_test.go
connector.go
const.go
errors.go
example_test.go
export_test.go
multi/config.lua
multi/multi.go
multi/multi_test.go
prepared.go
request.go
request_test.go
response.go
tarantool_test.go
test_helpers/request_mock.go
test_helpers/utils.go

This patch adds the support of prepared statements.
Added a new type for handling prepared statements.
Added new methods for connector's interface in connector.go.
Added new IPROTO-constants for support of prepared statements
in const.go. Updated multi-package for corresponding it to connector's
interface.
Added a new function for checking the count of prepared statements in
config.lua in tests for Prepare and Unprepare.
Added benchmarks for SQL-select prepared statement.
Added examples of using Prepare in example_test.go.
Fixed some grammar inconsistencies for the method Execute.
Updated CHANGELOG.md.
Follows up #62
Closes #117
Prepared Statement is just an object only having a constructor.
All requests get constructed with request objects.
Single connection usage:
```go
conn, err := …
```

sql: support prepared statements

---

CHANGELOG.md
connection.go
example_test.go
prepared.go
request.go
tarantool_test.go
test_helpers/request_mock.go

This patch adds the support of using context in API. The API is based
on using request objects. Added tests that cover almost all cases of
using the context in a query. Added benchamrk tests are equivalent to
other, that use the same query but without any context.
Closes #48
#48
Context support supposes a mechanism of canceling requests to instance.
The canceling happens when the timeout/deadline is over or the cancel function is called.
Also contexts may keep key-value inside.
There are two ways of representing context in API.
Standard `http` package supports it inside the Request object.
```go
func NewRequestWithContext(ctx context.Context, method, url string, body io.Reader) (*Request, error)
func (r *Request) Context() context.Context
```
For outgoing client requests, …

Add context support

---

CHANGELOG.md
connection.go
future.go
future_test.go

The pull request contains two fixes:
1. bugfix: race conditions in Future methods
Before the patch it may be possible to close several times fut.ready and fut.done channels from the public API calls.
2. bugfix: usage of nil in Connection.peekFuture()
It may be possible to get a nil value from conn.getFutureImp(). We need to check the value before using.

fixes for race conditions with Future objects

---

CHANGELOG.md
config.lua
connection.go
connection_pool/config.lua
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go
connection_pool/example_test.go
connector.go
const.go
example_test.go
export_test.go
multi/config.lua
multi/multi.go
multi/multi_test.go
prepared.go
request_test.go
stream.go
tarantool_test.go
test_helpers/main.go
test_helpers/utils.go

The main purpose of streams is transactions via iproto.
Since v. 2.10.0, Tarantool supports streams and
interactive transactions over them. Each stream
can start its own transaction, so they allows
multiplexing several transactions over one connection.
API for this feature is the following:
* `NewStream()` method to create a stream object for `Connection`
and `NewStream(userMode Mode)` method to create a stream object
for `ConnectionPool`
*  stream object `Stream` with `Do() method and
new request objects to work with stream,
`BeginRequest` - start transaction via iproto stream;
`CommitRequest` - commit transaction;
`RollbackRequest` - rollback transaction.
Closes #101

streams: interactive transactions and streams support

---

connection_pool/const.go
decimal/bcd.go
future.go
queue/queue.go
schema.go
ssl_test.go
uuid/uuid.go

golangci-lint on GitHub Actions uses a latest gofmt from GoLang 1.19. The patch contains changes from gofmt 1.19 run to fix golangci-lint check on CI.

code health: run gofmt from GoLang 1.19

---

CHANGELOG.md
datetime/adjust.go
datetime/config.lua
datetime/datetime.go
datetime/datetime_test.go
datetime/example_test.go
datetime/interval.go
datetime/interval_test.go
datetime/msgpack.go
datetime/msgpack_v5.go

The patch adds interval [1] support for datetime. Except encoding/decoding interval values from MessagePack, it adds a several functions for addition and substraction Interval and Datetime types in GoLang. Reproducing, thus, arithmetic operations from the Lua implementation [2].
1. https://github.com/tarantool/tarantool/wiki/Datetime-Internals#interval-arithmetic
2. https://github.com/tarantool/tarantool/wiki/Datetime-Internals#arithmetic-operations
Closes #165

datetime: add interval support

---

CHANGELOG.md
decimal/bcd.go
decimal/decimal.go

The patch hides the implementation details of the Decimal type from
documentation. It provides comments for Decimal.MarshalMsgpack and
Decimal.UnmarshalMsgpack.
How-to test:
1. Run: `$ godoc -http=:8080` in the go-tarantool folder.
2. Open http://localhost:8080/pkg/github.com/tarantool/go-tarantool/decimal/ .
Closes #201

doc: fix markdown for the decimal package 

---

CHANGELOG.md
Makefile
queue/config.lua
queue/const.go
queue/queue.go
queue/queue_test.go
queue/task.go

* bump queue package version to 1.2.0 [1]
* add Task.Touch(): increases TTR and/or TTL for tasks [2]
* add Queue.Cfg(): set queue settings [3]
* add Queue.ReleaseAll(): releases all taken tasks [4]
* add Queue.State(): returns a current queue state [5]
* add Queue.Identify(): identifies a shared session [6]
1. https://github.com/tarantool/queue/releases/tag/1.2.0
2. https://github.com/tarantool/queue/blob/1.2.0/README.md?plain=1#L562-L576
3. https://github.com/tarantool/queue/blob/1.2.0/README.md?plain=1#L450-L463
4. https://github.com/tarantool/queue/blob/1.2.0/README.md?plain=1#L698-L704
5. https://github.com/tarantool/queue/blob/1.2.0/README.md?plain=1#L377-L391
6. https://github.com/tarantool/queue/blob/1.2.0/README.md?plain=1#L465 …

api: support queue 1.2.0

---

CHANGELOG.md
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go
connection_pool/const.go
connection_pool/example_test.go
connection_pool/round_robin.go
connection_pool/round_robin_test.go
connection_pool/state.go

The patchset contains a number of different fixes for the connection_pool package. I tried to make the changes in small commits so that it would be easier to review them. I recommend to review the changes one by one commit.

Several fixes for the connection_pool subpackage

---

CHANGELOG.md
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go

ConnectionHandler provides callbacks for components interested in handling changes of connections in a ConnectionPool.
We have to take into account that user callbacks can take an indefinite amount of time. The simplest solution is to process each connection in a separate goroutine. This should not affect to performance because most of the time these goroutines are blocked.
Closes #178
The pull request is based on #208. You need to review **only a last commit** until #208 is not merged.

api: add ConnectionHandler to the connection_pool

---

CHANGELOG.md
Makefile
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go
connection_pool/connector.go
connection_pool/connector_test.go
connection_pool/const.go
connection_pool/example_test.go
connection_pool/msgpack_helper_test.go
connection_pool/msgpack_v5_helper_test.go
connection_pool/pooler.go
multi/multi_test.go
queue/example_connection_pool_test.go
queue/queue_test.go
queue/testdata/config.lua
queue/testdata/pool.lua
test_helpers/main.go

The patchet allows to use the queue subpackage with the connection_pool subpackage:
1. It adds missed `Execute*` methods to ConnectionPool.
2. It adds ConnectorAdaptor to the connection_pool subpackage to be able to use ConnectionPool as Connector.
Finally, it adds an example how-to use a Queue with ConnectionPool.
Closes #176

api: queue works with connection_pool

---

CHANGELOG.md
decimal/bcd.go

The patch replaces usage of a test function GetNumberLength by a package-level function getNumberLength in the decimal package code.

bugfix: decimal use a test function

---

CHANGELOG.md
datetime/datetime.go
datetime/datetime_test.go

Tarantool used to ignore timezone difference (offset) for a datetime interval calculations due to a bug [1]. We have to fix it too since we relied on the wrong behavior.
1. https://github.com/tarantool/tarantool/issues/7698
didn't forget about (remove if it is not applicable):

datetime: fix interval arithmetic with timezones

---

CHANGELOG.md
connection_pool/connection_pool_test.go
queue/example_connection_pool_test.go
queue/queue.go
queue/task.go

The flaky test output:
```
=== RUN   Example_connectionPool
--- FAIL: Example_connectionPool (1.01s)
got:
Master 127.0.0.1:3014 is ready to work!
A Queue object is ready to work.
Send data: test_data
Master 127.0.0.1:3015 is ready to work!
task.Data() == nil
want:
Master 127.0.0.1:3014 is ready to work!
A Queue object is ready to work.
Send data: test_data
Master 127.0.0.1:3015 is ready to work!
Got data: test_data
```
We get a nil task if a ConnectionPool does not yet detect master->replica role switch. We need to add additional check for the case to make the test output deterministic.

queue: fix flaky Example_connectionPool 

---

client_tools.go
config.lua
example_test.go
tarantool_test.go

The patch adds examples for:
* Connection.GetTyped() method
* IntKey type
* UintKey type
* StringKey type
* IntIntKey type
Closes #196

doc: add examples for GetTyped() and custom keys

---

.github/workflows/testing.yml

It would be more correct to use a merge request commit instead of original commit for pull_request_target.

ci: use merge commit for pull_request_target

---

CHANGELOG.md
decimal/decimal.go

The patch replaces usage of a test variable DecimalPrecision by a package-level variable decimalPrecision in the decimal package code.
See:
1. https://github.com/tarantool/go-tarantool/blob/48cf0c75b3869e54fc47881f0a1323612c3694fe/decimal/decimal.go#L36
2. https://github.com/tarantool/go-tarantool/blob/48cf0c75b3869e54fc47881f0a1323612c3694fe/decimal/export_test.go#L16

bugfix: decimal uses a test variable

---

CHANGELOG.md
connection.go
connection_pool/connection_pool.go
connection_pool/example_test.go
connection_test.go
const.go
example_test.go
export_test.go
multi/multi.go
protocol.go
protocol_test.go
response.go
tarantool_test.go
test_helpers/utils.go

api: support iproto feature discovery
Since version 2.10.0 Tarantool supports feature discovery [1]. Client
can send client protocol version and supported features and receive
server protocol version and supported features information to tune
its behavior.
After this patch, the request will be sent on `dial`, before
authentication is performed. Connector stores server info in connection
internals. User can also set option RequiredProtocolVersion and
RequiredProtocolFeatures to fast fail on connect if server does
not provide some expected feature, similar to net.box opts [2]. It is
not clear how connector should behave in case if client doesn't support
a protocol feature or protocol version, see [3]. For now we decided not
to check requirements on client side.
Feature check iterates over …

api: support iproto feature discovery

---

CHANGELOG.md
box_error.go
box_error_test.go
config.lua
const.go
errors.go
example_test.go
msgpack.go
msgpack_helper_test.go
msgpack_v5.go
msgpack_v5_helper_test.go
protocol.go
response.go
tarantool_test.go
test_helpers/utils.go

Merge after #226
Since 2.4.1 IPROTO_ERROR (0x31) is renamed to IPROTO_ERROR_24 and IPROTO_ERROR name is used for 0x52 constant describing extended error info [1].
1. https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-error-type
Part of #209
Since Tarantool 2.4.1, iproto error responses contain extended info with backtrace [1]. After this patch, Error would contain ExtendedInfo field (BoxError object), if it was provided. Error() handle now will print extended info, if possible.
1. https://www.tarantool.io/en/doc/latest/dev_guide/internals/box_protocol/#responses-for-errors
Part of #209
Tarantool supports error extension type since version 2.4.1 [1], encoding was introduced in Tarantool 2.10.0 [2]. This patch introduces the support of Tarantool error …

api: support errors extended information and error type in MessagePack

---

.github/workflows/check.yaml
.github/workflows/testing.yml
CHANGELOG.md
connection.go
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go
connection_pool/connector.go
connection_pool/connector_test.go
connection_pool/example_test.go
connection_pool/pooler.go
connection_pool/round_robin.go
connection_pool/round_robin_test.go
connection_pool/watcher.go
connector.go
const.go
example_test.go
multi/multi.go
multi/multi_test.go
protocol.go
request.go
request_test.go
tarantool_test.go
test_helpers/request_mock.go
test_helpers/utils.go
watch.go

A user can create watcher by the Connection.NewWatcher() call:
```Go
watcher = conn.NewWatcker("key", func(event WatchEvent) {
// The callback code.
})
```
After that, the watcher callback is invoked for the first time. In this case, the callback is triggered whether or not the key has already been broadcast. All subsequent invocations are triggered with box.broadcast() called on the remote host. If a watcher is subscribed for a key that has not been broadcast yet, the callback is triggered only once, after the registration of the watcher.
If the key is updated while the watcher callback is running, the callback will be invoked again with the latest value as soon as it returns.
Multiple watchers can be created for one key.
If you don’t need the watcher anymore, you can unregister it using …

api: add events subscription support

---

.github/workflows/testing.yml
CHANGELOG.md
auth.go
auth_test.go
config.lua
connection.go
connection_pool/watcher.go
const.go
protocol.go
request.go
response.go
ssl_test.go
tarantool_test.go
test_helpers/main.go

The authentication method works only with Tarantool EE [1].
1. https://github.com/tarantool/enterprise_doc/issues/206
Closes https://github.com/tarantool/go-tarantool/issues/243

api: add pap-sha256 auth support

---

.github/workflows/check.yaml

The patch adds a second golangci-lint run that prints errors in human-readable format [1].
1. https://github.com/golangci/golangci-lint-action/issues/119
Closes #231
The first run of golangci-lint prints errors in GitHub Actions format:
The second run in human-readable format:
Unfortunately, it doesn't work in one run and we need two different ones.

ci: improve golangci-lint output

---

CHANGELOG.md
connection.go
request_test.go
tarantool_test.go

The patch makes the test more deterministic. It helps to avoid
canceling a request with an already received response.
Closes #244

bugfix: flaky TestClientRequestObjectsWithContext 

---

CHANGELOG.md
multi/multi_test.go

After the fix the test stops tarantool intances to avoid concurrent reconnects by a ConnectionMulti instance.
Closes #234

bugfix: flaky multi/TestDisconnectAll

---

CHANGELOG.md
Makefile
connection.go
errors.go
shutdown_test.go
test_helpers/main.go
test_helpers/utils.go

If connected to Tarantool 2.10 or newer, after this patch a connection supports server graceful shutdown [1]. In this case, server will wait until all client requests will be finished and client disconnects before going down (server also may go down by timeout). Client reconnect will happen if connection options enable reconnect.
1. https://www.tarantool.io/en/doc/latest/dev_guide/internals/iproto/graceful_shutdown/
Closes #214

Graceful shutdown

---

README.md
tarantool_test.go

Technically, the connector can now work with Tarantool 1.6+. But we decided to simplify our CI and do not declare support for older versions [1].
1. https://github.com/tarantool/go-tarantool/pull/198

readme: support Tarantool 1.10+

---

.github/workflows/testing.yml
CHANGELOG.md
CONTRIBUTING.md
Makefile
connection.go
connection_pool/connection_pool_test.go
connection_pool/watcher.go
future_test.go
multi/multi.go
multi/multi_test.go
queue/example_connection_pool_test.go
schema.go

The patchset adds tests with race detector. It also fixes founded problems.
You could review commits one by one with the command:
```bash
$ go test -race -v ./...
```
Closes #218

ci: add tests with data race detector

---

CONTRIBUTING.md

Moving "Recommendations for how to achieve stable results" to [tarantool's wiki](https://github.com/tarantool/tarantool/wiki/Benchmarking) as discussed.

doc: move recommendations to a tarantool's wiki

---

CHANGELOG.md
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go

The ConnectionPool didn't close a connection if it couldn't get a role when checking the connection.
Closes #272

pool: handle disconnection with Opts.Reconnect

---

.github/workflows/testing.yml
connection_pool/connection_pool_test.go
multi/multi_test.go
queue/queue_test.go

Added macOS testing into ci.
- [not needed] Tests
- [Added] Changelog
- [not needed] Documentation 
Closes #157

ci: Add testing on macOS

---

const.go

add missing constant from https://github.com/tarantool/tarantool/blob/680990a082374e4790539215f69d9e9ee39c3307/src/box/iterator_type.h
fixes https://github.com/tarantool/go-tarantool/issues/285

add missing iterator constant

---

.github/workflows/testing.yml

The semantics of the `tt install` command have been updated [1]. A default installation path have been updated too.
1. https://github.com/tarantool/tt/commit/5bec7c1c0f1ce697ea457f8aa06ec6d151ea5e94

ci: fix Tarantool master installation

---

CHANGELOG.md
Makefile
config.lua
connection_pool/connection_pool_test.go
crud/example_test.go
crud/tarantool_test.go
crud/testdata/config.lua
datetime/datetime_test.go
decimal/decimal_test.go
decimal/example_test.go
example_test.go
multi/example_test.go
multi/multi_test.go
queue/example_connection_pool_test.go
queue/example_msgpack_test.go
queue/queue.go
queue/queue_test.go
queue/testdata/pool.lua
schema.go
settings/tarantool_test.go
shutdown_test.go
ssl_test.go
tarantool_test.go
uuid/uuid_test.go

Fixed many flaky tests for macOs.
Closes #277
Closes #278 
Closes #282
Closes #288
Closes #291

Fix many flaky tests on macOs

---

CHANGELOG.md

The release adds pagination support and wrappers for the crud module.
There are no breaking changes in the release.
* Support pagination (#246).
* Support CRUD API (#108).
* An ability to replace a base network connection to a Tarantool instance (#265).
* A Makefile target to test with race detector (#218).
* Missed iterator constant (#285).
* Several non-critical data race issues (#218).
* Build on Apple M1 with OpenSSL (#260).
* ConnectionPool does not properly handle disconnection with Opts.Reconnect set (#272).
* Connect() panics on concurrent schema update (#278).
* Wrong Ttr setup by Queue.Cfg() (#278).
* Flaky queue/Example_connectionPool (#278).
* Flaky queue/Example_simpleQueueCustomMsgPack (#277).
* queue module version bumped to 1.3.0 (#278).

Release 1.11.0

---

CHANGELOG.md
settings/tarantool_test.go
tarantool_test.go

New behavior: SELECT scan queries are only allowed if the SEQSCAN keyword is used correctly[1].
1. https://www.tarantool.io/en/doc/latest/reference/reference_lua/compat/sql_seq_scan_default/
https://github.com/tarantool/tarantool/pull/8602

test: fix compatibility with Tarantool master

---

CHANGELOG.md
connection.go
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go
connection_pool/example_test.go
connection_pool/state.go
example_test.go
shutdown_test.go

CloseGraceful closes Connection gracefully. Unlike Connection.Close() it waits for all requests to complete.
CloseGraceful closes ConnectionPool gracefully. Unlike ConnectionPool.Close() it waits for all requests to complete.
Changes to the connection pool may seem too global, but it will simplify #290 .
Closes #257

api: add Connection.CloseGraceful() and ConnectionPool.CloseGraceful()

---

CHANGELOG.md
connection_pool/connection_pool.go
connection_pool/connection_pool_test.go

* ConnectionPool.Add() allows to add a new endpoint into a pool.
* ConnectionPool.Remove() allows to remove an endpoint from a pool.
Closes #290

api: ConnectionPool.Add()/ConnectionPool.Remove()

---

connection_pool/connection_pool.go
connection_pool/connection_pool_test.go

We need to add non-added endpoint to avoid `endpoint exist` error.
See:
```
2023-06-05T14:18:52.4408505Z === RUN   TestAdd_CloseGraceful_concurrent
2023-06-05T14:18:52.4468977Z     connection_pool_test.go:371: 
2023-06-05T14:18:52.4469460Z         	Error Trace:	connection_pool_test.go:371
2023-06-05T14:18:52.4469950Z         	            				asm_amd64.s:1571
2023-06-05T14:18:52.4470246Z         	Error:      	Not equal: 
2023-06-05T14:18:52.4470864Z         	            	expected: &errors.errorString{s:"endpoint exist"}
2023-06-05T14:18:52.4471538Z         	            	actual  : &errors.errorString{s:"pool is closed"}
2023-06-05T14:18:52.4471864Z         	            	
2023-06-05T14:18:52.4472171Z         	            	Diff:
2023-06-05T14:18:52.4472692Z         	            	--- Expected …
```

bugfix: flaky TestAdd_CloseGraceful_concurrent

---

CHANGELOG.md
config.lua
tarantool_test.go

Added test for IsNullable Field flag decoding.

test: add test for IsNullable Field flag

---

CHANGELOG.md
decimal/decimal_test.go

[See](https://github.com/tarantool/go-tarantool/actions/runs/5197333156/jobs/9372037885):
```
2023-06-07T07:52:34.7468540Z # github.com/tarantool/go-tarantool/decimal.test
...
2023-06-07T07:52:36.3115720Z --- FAIL: TestSelect (0.53s)
2023-06-07T07:52:36.3119070Z     decimal_test.go:503: Decimal insert failed: client timeout for request 10 (0x4003)
```
We forgot to increase the timeout [1] when we fixed tests for macos.
1. https://github.com/tarantool/go-tarantool/commit/521c0c34804e93cd2648c3b5c27bc7194d3870d0

test: fix flaky decimal.TestSelect

---

.github/workflows/testing.yml

This patch adds the condition to run this workflow only for main repo. It helps to avoid failed CI on forks.
As example of the problem see: https://github.com/kokizzu/go-tarantool

ci: don't run EE tests on forks by default

---

CHANGELOG.md
queue/queue.go

The `identify()` function expects the UUID argument to be a plain string while the go connector encodes it in MsgPack as a binary blob (`MP_BIN`). This works fine for now because Tarantool stores `MP_BIN` data in a string when decoded to Lua but this behavior is going to change soon: we're planning to introduce the new Lua type for binary data and update the MsgPack decoder to store `MP_BIN` data in a varbianry object instead of a plain string.
Let's prepare for that by converting the UUID data to a string before encoding.
Needed for tarantool/tarantool#1629

queue: encode UUID argument of `identify()` as string instead of binary

---

CHANGELOG.md
pool/connection_pool_test.go
pool/round_robin.go

The `r.current` value can be changed by concurrent threads because the change happens under read-lock. We could use the atomic counter for a current connection number to avoid the race condition.
Closes #309

pool: fix race condition at GetNextConnection()

---

CHANGELOG.md
decimal/bcd.go
decimal/decimal.go
decimal/decimal_test.go
decimal/export_test.go
decimal/fuzzing_test.go

The `scale` value in `MP_DECIMAL` may be negative [1]. We need to handle the case.
1. https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-decimal-type

decimal: incorrect MP_DECIMAL decoding with scale < 0

---

CHANGELOG.md
README.md
datetime/datetime.go
datetime/datetime_test.go
datetime/example_test.go
decimal/decimal.go
decimal/decimal_test.go
decimal/example_test.go

After the patch Decimal, Datetime and uuid used in the same way: by a value.
Part of #238

api: unify usage of external types

---

CHANGELOG.md
crud/example_test.go
crud/select.go

The patch fixes a typo that made it impossible to setup `SelectOpts.After`, `SelectOpts.BatchSize` and `SelectOpts.ForceMapCall`.
Part of #320

crud: fix options for SelectRequest

---

CHANGELOG.md
connection_pool/connection_pool_test.go
connection_pool/round_robin.go
crud/example_test.go
crud/select.go
decimal/bcd.go
decimal/decimal.go
decimal/decimal_test.go
decimal/export_test.go
decimal/fuzzing_test.go
queue/queue.go

The patch release imports fixes from the master branch.
There are no breaking changes in the release.
* Flaky decimal/TestSelect (#300).
* Race condition at roundRobinStrategy.GetNextConnection() (#309).
* Incorrect decoding of an MP_DECIMAL when the `scale` value is negative (#314).
* Incorrect options (`after`, `batch_size` and `force_map_call`) setup for crud.SelectRequest (#320).
* Change encoding of the queue.Identify() UUID argument from binary blob to plain string. Needed for upgrade to Tarantool 3.0, where a binary blob is decoded to a varbinary object (#313).

Release 1.12.1

---

CHANGELOG.md
crud/error.go
crud/example_test.go
crud/result.go
crud/result_test.go

This patch adds `operation_data` decoding for the `crud.Error`.
The `operation_data` type is determined as `rowType` in `crud.Result`.
Also, according to [1], an error can contain one of the following:
- an error
- an array of errors
- nil
So the error decoding logic has been modified to consider each case, in order to avoid comparing an error to nil.
1. https://github.com/tarantool/crud/tree/master#api
Closes #330

crud: support `operation_data` field in errors

---

CHANGELOG.md
Makefile
crud/example_test.go
crud/get.go
crud/options.go
crud/result.go
crud/select.go
crud/tarantool_test.go

This PR introduces missing crud module options and a couple of bugfixes/doc improvements that was discovered while solving the original issue.

CRUD API improvements

---

CHANGELOG.md
README.md
connection.go
crud/example_test.go
crud/tarantool_test.go
datetime/example_test.go
decimal/example_test.go
dial.go
dial_test.go
example_custom_unpacking_test.go
example_test.go
export_test.go
go.mod
go.sum
pool/connection_pool.go
pool/connection_pool_test.go
pool/example_test.go
queue/example_connection_pool_test.go
queue/example_msgpack_test.go
queue/example_test.go
settings/example_test.go
shutdown_test.go
ssl.go
ssl_disable.go
ssl_test.go
tarantool_test.go
test_helpers/main.go
test_helpers/pool_helper.go
test_helpers/utils.go
uuid/example_test.go

`connection.Connect` and `pool.Connect` no longer return non-working connection objects. Those functions now accept context as their first arguments, which user may cancel in process.
`connection.Connect` will block until either the working connection created (and returned), `opts.MaxReconnects` creation attempts were made (returns error) or the context is canceled by user (returns error too).
Closes #136

api: add context to connection create

---

CHANGELOG.md
Makefile
crud/example_test.go
crud/schema.go
crud/tarantool_test.go

Support `crud.schema` request [1] and response parsing.
1. https://github.com/tarantool/crud/pull/380

crud: support schema

---

Makefile

Needed for tarantool/tarantool#8147

crud: bump rocks minor version with compatibility fixes

---

CHANGELOG.md
README.md
connection.go
connection_test.go
dial_test.go
example_test.go
export_test.go
go.mod
go.sum
pool/connection_pool.go
pool/connection_pool_test.go
pool/example_test.go
protocol.go
protocol_test.go
request.go
request_test.go
response.go
shutdown_test.go
tarantool_test.go
test_helpers/utils.go

Added support of `IPROTO_WATCH_ONCE` request type.
It works only for Tarantool version >= 3.0.0-alpha1.
Replaced the local `ProtocolFeature` type with the `iproto.Feature`.
Replaced local `Feature` constants with their `iproto.IPROTO_FEATURE_` analogues.
Closes #337

api: support `IPROTO_WATCH_ONCE` request type

---

CHANGELOG.md
README.md
crud/count.go
crud/get.go
crud/options.go
crud/request_test.go
crud/select.go
crud/tarantool_test.go

`Timeout` is an option supported for all crud operations using VShard API. In Lua, timeout has `number` type, so float values are allowed. Float timeouts can be useful to set the timeout less than a second. After this patch, `Timeout` will be an optional float64 instead of an optional int.
This is a breaking change.
CRUD allows to use negative timeouts. This approach does not make any sense for an operation: for example, initial schema fetch will fail. Since the module itself does not check for a negative value argument, we do not forbid it here too.
I didn't forget about:
Closes #342

crud: change timeout option type

---

datetime/datetime.go

Since NewDatetime was renamed to MakeDatetime, I renamed it in the comment section too. 

doc: rename NewDatetime to MakeDatetime in comments

---

CHANGELOG.md
crud/count.go
crud/options.go
crud/select.go
crud/tarantool_test.go

`yield_every` was introduced to crud.count and crud.select in crud 1.1.1 [1]. The option is already supported for count requests, but select request misses it. This patch adds the option.
1. https://github.com/tarantool/crud/releases/tag/1.1.1
I didn't forget about:

crud: support yield_every in select

---

.github/workflows/testing.yml
CHANGELOG.md
README.md
connection.go
crud/request_test.go
example_test.go
export_test.go
protocol.go
request.go
request_test.go
schema.go
settings/request_test.go
tarantool_test.go

Support `IPROTO_FEATURE_SPACE_AND_INDEX_NAMES` for Tarantool version >= 3.0.0-alpha1. It allows to use space and index names in requests instead of their IDs.
`ResolveSpaceIndex` function for `SchemaResolver` interface split into two: `ResolveSpace` and `ResolveIndex`. `NamesUseSupported` function added into the interface to get information if usage of space and index names is supported.
`Schema` structure no longer implements `SchemaResolver` interface.
Update Tarantool EE version 1.10.11 to 1.10.15, 2.10.0 to 2.10.8 and 2.11.0 to 2.11.1. This was done because of the one flacking test: https://github.com/tarantool/go-tarantool/actions/runs/6805504621/job/18505152412
Closes #338

api: support `IPROTO_FEATURE_SPACE_AND_INDEX_NAMES`

---

CHANGELOG.md
crud/options.go
crud/request_test.go
crud/schema.go
crud/tarantool_test.go

Support missing `crud.schema` options. Clean up some other crud patches mistakes.
Follows #336, #350

crud: support schema opts

---

CHANGELOG.md
README.md
client_tools.go
client_tools_test.go
connector.go
crud/operations.go
crud/operations_test.go
crud/tarantool_test.go
example_test.go
export_test.go
pool/connection_pool.go
pool/connection_pool_test.go
pool/connector.go
pool/connector_test.go
pool/pooler.go
request.go
request_test.go
tarantool_test.go
test_helpers/utils.go

Splice update operation (`:`) accepts 5 and only 5 arguments. It was parsed and encoded incorrectly with only 3 argument (as every other update operations).
Also fixed the same operation for the crud.
`Op` struct made private.
Change all `Upsert` and `Update` requests to accept `*tarantool.Operations` as `ops` parameters instead of the `interface{}`.
Closes #348

api: fix splice update operation

---

CHANGELOG.md
README.md
connection.go
example_test.go
schema.go
tarantool_test.go

Write a helper function to load the actual schema for the user.
Previously we stored actual schema in a private `schemaResolver` field and `Schema` field was used only to get a current schema. But now because of the new function, we don't need to store the `Schema` as a different field. So `Schema` was also removed.
To update the schema, one needs to use `GetSchema` + `SetSchema` in pair. `SetSchema(Schema)` replacing the `OverrideSchema(*Schema)`.
`Spaces` and `SpacesById` fields of the `Schema` struct store spaces by value.
`Fields` and `FieldsById` fields of the `Space` struct store fields by value. `Index` and `IndexById` fields of the `Space` struct store indexes by value.
`Fields` field of the `Index` struct store `IndexField` by value.
I didn't forget about (remove if it is not …

api: write a connection schema getter

---

connection.go

Changed type of 'length' variable in 'read' function to avoid overflow when calculating it.
- [ not needed] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [not needed ] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)
- [not needed ] Documentation (see [documentation](https://go.dev/blog/godoc) for documentation style guide)

connection: fix svacer issue

---

go.mod
go.sum

The patch bumps the go-iproto dependency to the latest release version.

mod: bump go-iproto to v1.0.0

---

CHANGELOG.md
Makefile
connection.go
crud/tarantool_test.go
settings/tarantool_test.go
tarantool_test.go

The patch release imports fixes from the master branch.
There are no breaking changes in the release.
* Tests with crud 1.4.0 (#336).
* Tests with case sensitive SQL (https://github.com/tarantool/go-tarantool/pull/341).
* Potentially packet length overflow when reading (https://github.com/tarantool/go-tarantool/pull/361).

Release 1.12.2

---

.github/workflows/check.yaml
.github/workflows/reusable_testing.yml
.github/workflows/testing.yml
Makefile

Part of tarantool/tarantool#9443

ci: remove tarantoolctl

---

CHANGELOG.md
README.md
dial_test.go
pool/connection_pool.go
pool/connection_pool_test.go
pool/example_test.go
pool/round_robin.go
pool/round_robin_test.go
queue/example_connection_pool_test.go

The type Instance:
```Go
type Instance struct {
// Name is an unique name of the instance.
Name   string
// Dialer will be used to create a connection to the instance.
Dialer tarantool.Dialer
// Opts will be used to specify a connection options.
Opts   tarantool.Opts
}
```
The type allows to specify a dialer and connection options per a pool instance. It is used in `pool.Connect`, `pool.ConnectWithOpts` and `pool.Add` to specify an instance configuration now.
Closes https://github.com/tarantool/go-tarantool/issues/356

pool: add Instance type

---

CHANGELOG.md
README.md
crud/example_test.go
crud/insert_many.go
crud/object.go
crud/replace_many.go
crud/tuple.go

It was a mistake to use `[]interface{}` or `[]msgpack.CustomEncoder` as types for an array of tuples or an array of objects. Users were unable to use slices of custom types as incoming values.
The patch now allows the use of `interface{}` as incoming values. It makes it easier to use the API, but users need to be more careful. Therefore, we have also added examples.
Closes #365

crud: allow interface{} as values for *ManyRequest

---

CHANGELOG.md
README.md
pool/connection_pool.go
pool/connection_pool_test.go

From a user's perspective, it is useful to add all target instances to the pool, even some that are not currently unavailable. This way the user don’t have to keep track of the list of actually added instances.
The patch make it possible.
Closes #372

pool: add a connection even on connection error

---

CHANGELOG.md
connection.go
dial.go
dial_test.go
ssl_test.go
tarantool_test.go

To disable SSL by default we want to transfer `OpenSslDialer` to the go-openssl repository. In order to do so, we need to minimize the amount of copy-paste of the private functions.
`AuthDialer` is created as a dialer-wrapper, that calls authentication methods.
`ProtoDialer` is created to check the `ProtocolInfo` in the created connection.
`GreetingDialer` is created to fill the `Greeting` in the created connection.
Part of #301

 api: add helper Dialer implementations

---

CHANGELOG.md
pool/connection_pool.go
pool/connection_pool_test.go

The method allows to execute a request on the target instance in a pool.
Closes #376

pool: add a new method `Pool.DoInstance`

---

.github/workflows/reusable_testing.yml
.github/workflows/testing.yml
CHANGELOG.md
Makefile
README.md
connection.go
future_test.go
go.mod
response.go
test_helpers/main.go
test_helpers/response.go

Bump go version to 1.20.
Update ci to use go version 1.20 and newer.
Remove usage of the deprecated libraries.
Part of #378

go: bump go to 1.20

---

CHANGELOG.md
README.md
future.go

The method causes an improper error handling because it returns an error only from a client side. Therefore, it is not enough to simply check the error to find out that the request was not completed.
A user should check an error from `Future.Get()` or `Future.GetTyped()`. In addition, the user can find out whether there was an error without decoding the response body with `Future.GetResponse()`, see `ExampleErrorNo`.

api: remove Future.Err()

---

CHANGELOG.md
MIGRATION.md
README.md

There are a lot of changes in the new major version. The main ones:
* The `go_tarantool_call_17` build tag is no longer needed, since by default the `CallRequest` is `Call17Request`.
* The `go_tarantool_msgpack_v5` build tag is no longer needed, since only the `msgpack/v5` library is used.
* The `go_tarantool_ssl_disable` build tag is no longer needed, since the connector is no longer depends on `OpenSSL` by default. You could use the external library [go-tlsdialer](https://github.com/tarantool/go-tlsdialer) to create a connection with the `ssl` transport.
* Required Go version is `1.20` now.
* The `Connect` function became more flexible. It now allows to create a connection with cancellation and a custom `Dialer` implementation.
* It is required to use `Request` implementation types with …

Release 2.0.0

---

CHANGELOG.md
pool/connection_pool.go
pool/connection_pool_test.go

ConnectionPool.Remove() does not notify a ConnectionHandler on an instance removing from the pool.

pool: fix notify on remove a connection

---

CHANGELOG.md
pool/config.lua
pool/connection_pool.go
pool/connection_pool_test.go
tarantool_test.go
test_helpers/utils.go

Starting from Tarantool version >= 3.0.0 `WatchOnce` requset is supported. So we can get instance status using this request instead of calling `box.info`.
This way user can add instances to the `ConnectionPool` without the `execute` access.
Closes #380

pool: get instance status from `WatchOnce` request

---

CHANGELOG.md
pool/connection_pool.go

Description at: #389 
I added some logging for ConnectionPool.tryConnect err result.

#389: add some logging for error of ConnectionPool.tryConnect

---

config.lua

We are going to add missing 'user' payload field for ACCESS_DENIED error which will break current tests. Let fix tests to allow adding new payload fields for errors.
This is another place where we test for payload equality.
Need for https://github.com/tarantool/tarantool/issues/9108

test: use coverage instead of equality to test error payload 2

---

CHANGELOG.md
pool/pooler.go

added methods that are implemented but not included in the pooler interface

pool: add missing methods to the pooler interface

---

.github/workflows/testing.yml
Makefile

Currently `make deps`, which is used for tests, installs specified version of `crud`. Such approach complicates integration with Tarantool: when a patch in Tarantool breaks integration with both `crud` and `go-tarantool` (because it uses `crud`), one needs to fix `crud`, then release it and then bump it to the new version in makefile of `go-tarantool`. Let's simplify this process - simply install `crud` from its master for tests. Note that such approach has a drawback - any commit in `crud` can break integration with `go-tarantool`.
The patch is intended to fix failing integration [test](https://github.com/tarantool/tarantool/actions/runs/10263183465/job/28394723156?pr=9960#step:9:1075) in `tarantool`.
Along the way, the patch drops `macOS-11` runners since they are not supported by …

test: install crud from master

---

CHANGELOG.md
connection.go
example_test.go
tarantool_test.go

Log the probable reason for unexpected requestId.
Add requestId info to context done error message.

api: more informative request canceling

---

arrow/tarantool_test.go

The pull request changes [1] changes an error message on arrow decoding. The patch replaces a check of error message to a check of error code as it is a more stable check. However, the code is changed too. So as a temporary solution we need to work with both codes at the same time.
1. https://github.com/tarantool/tarantool/pull/10665
Part of #415

tests: fix decode arrow check after update

---

.github/workflows/testing.yml
arrow/tarantool_test.go
go.mod
go.sum
test_helpers/main.go

Now it is difficult to determine a reason of a `tarantool --version` parsing error. The patch adds a command output to the error to make it easier.
The patchset includes other non-critical updates:
The macos-12 is no longer supported by GitHub.
The patch updates a check according to a latest Tarantool 3.3.0 release
Closes #415

tests: add output to a version parse error

---

CHANGELOG.md
box/box.go
box/box_test.go
box/example_test.go
box/info.go
box/request.go
box/tarantool_test.go
box/testdata/config.lua

implemented the box interface for tarantool with a small number of fields, which in the future can be supplemented
Closes: #410

box: first box and box.info implementation

---

pool/connection_pool.go

We need to reset an error to pool.ErrClosed in a Pool.Add() method if a pool already closed or closing in progress to make the behavior deterministic.

test: fix flaky TestAdd_Close_concurrent

---

CHANGELOG.md
connection.go
tarantool_test.go

We need to keep an existing schema resolver to avoid a schema reset after a reconnect. An another approach could be to get a schema on each reconnect, but we will change the expected behavior in this case: load a schema once on a first connect.

bugfix: schema is reset after a reconnect

---

CHANGELOG.md
box/info.go
box/info_test.go
box/tarantool_test.go
box/testdata/config.lua

Extend box information with replication fields.

Extend box information with replication fields

---

CHANGELOG.md
pool/connection_pool.go
pool/connection_pool_test.go

The Instance info has been added to ConnectionInfo, which is necessary to monitor the current state of the pool. This should help implement dynamic tracking of tarantool topology changes.

pool: add Instance info to ConnectionInfo

---

CHANGELOG.md
connection.go
tarantool_test.go

This patch makes Connect() retry connection attempts if opts.Reconnect is greater than 0. The delay between connection attempts is opts.Reconnect. If opts.MaxReconnects > 0 then the maximum number of attempts is equal to it, otherwise the maximum number of attempts is unlimited. Connect() now also blocks until a connection is established, provided context is cancelled or the number of attempts is exhausted.
Closes #436
Connect() now handles connection retries on its own. This simplifies connecting to Tarantool instances when there is no guarantee that the connection will be established on the first try.
Related issues: #436

api: block Connect() on failure if Reconnect > 0

---

CHANGELOG.md

The patch releases fixes expected Connect() behavior and reduces allocations.
- A usage of sync.Pool of msgpack.Decoder saves 2 object allocations per a response decoding.
- Connect() now retry the connection if a failure occurs and opts.Reconnect > 0. The number of attempts is equal to opts.MaxReconnects or unlimited if opts.MaxReconnects == 0. Connect() blocks until a connection is established, the context is cancelled, or the number of attempts is exhausted (#436).

Release v2.3.1

---

CHANGELOG.md
connection.go
dial.go
dial_test.go

NetDialer, GreetingDialer, AuthDialer and ProtocolDialer may not cancel Dial() on context expiration when network connection hangs.
The issue occurred because context wasn't properly handled during network I/O operations, potentially causing infinite waiting.
Part of TNTP-2018

dial: Connect() does not cancel by context if no i/o

---

CHANGELOG.md
pool/connection_pool.go
pool/connection_pool_test.go
tarantool_test.go

Previously, `pool.Connect` attempted to establish a connection one after another instance. It could cause the entire chain to hang if one connection hanged. Now connections are established in parallel. After the first successful connection, the remaining connections wait with a timeout of `pool.Opts.CheckTimeout`.
Closes #TNTP-2018

pool: fix pool.Connect if a server i/o hangs

---

CHANGELOG.md

This release improves the logic of `Connect` and `pool.Connect` in case of a hung I/O connection.
- Previously, `pool.Connect` attempted to establish a connection one after another instance. It could cause the entire chain to hang if one connection hanged. Now connections are established in parallel. After the first successful connection, the remaining connections wait with a timeout of `pool.Opts.CheckTimeout` (#444).
- Connect() may not cancel Dial() call on context expiration if network connection hangs (#443).
- pool.Connect() failed to connect to any instance if a first instance connection hangs (#444).

Release v2.3.2

---

CHANGELOG.md
connection.go
tarantool_test.go

Before this patch, `conn.c` was not checked for `nil` before calling its method. This could cause a panic if the connection was lost or closed.
Closes #438
Related issues: #438

api: fix panic in conn.NewWatcher()

---

CHANGELOG.md
schema.go
schema_test.go
tarantool_test.go

schema: move 'concurrent schema update' error to constants

---

.github/workflows/testing.yml

* Removed unsupported macos-13 from CI actions.
* Added new and supported by apple/github macos-15 and macos-26.
* Removed tests for 1.10 on macOS (they won't even build on new versions of llvm that are shipped with macos-14 and newer ones).
* Use actions-setup-cmake@v2 for new versions of macOS, since they are shipped with cmake 4.* or cmake 3.31, but supported cmake version for macOS is 3.29.x.

ci: fix actions on macOS flows
